### ISSUE TITLE
<figure> tag for individual team photo question

### ISSUE THREAD

**Issue by yvonne-liu** [FAC10/week1-Facalacalaca#75]
Is there a reason why these are in two different `<figure>` tags? Would it be better to put them either all in one tag, or in four individual tags? 

```
<figure>
  <img id="alexis" class="section_team_members" src="assets/square alexis.jpg" alt="Alexis">
  <img id="alice" class="section_team_members" src="assets/square alice.jpg" alt="Alice
</figure>
<figure>
  <img id="martha" class="section_team_members" src="assets/square martha.jpg" alt="Martha">
  <img id="samatar" class="section_team_members" src="assets/square samatar.jpg" alt="Samatar">
</figure>
```

**Comment by smarthutza** [comment]
We used <figure> twice because we don't want to occasionaly end up with 3 pictures on a line and the forth one on a different line. We want a) all pictures on one line or b) two pictures on two lines or c)all pictures one underneath each other. Never 3 and 1.
