### ISSUE TITLE
Gifs aren't an ideal file format for longer moving content

### ISSUE THREAD

**Issue by oliverjam** [FAC10/week1-Facalacalaca#77]
The gif you're using to show the coding screen recording is quite a large file and takes a while to load on mobile.

Using a `video` tag with an .mp4 file would probably be more efficient (the .mp4 format was designed to encode moving images efficiently, whereas .gifs are basically just tons of jpgs stuck together). Videos are also hardware-accelerated which makes them play more smoothly on mobile. Videos are also pausable and rewindable! :)

If you put `autoplay`, `loop` and `muted` attributes on the video tag then you'll get almost the same affect as a gif.

**Comment by alexis-l8** [comment]
Thanks for this suggestion. We will keep this in mind in future
